### ISSUE TITLE
No such file or directory: 'pdb4amber_nonprot.pdb'

### ISSUE THREAD

**Issue by ryan-224** [vanderkamp/enlighten2#3]
Hello,

Thanks for sharing the source code.

When I tried to run the prep.py with a pdb file, it raised an error, FileNotFoundError: [Errno 2] No such file or directory: 'pdb4amber_nonprot.pdb'.

May I know what is that file and how can I solve this?

Thanks

**Comment by kzinovjev** [comment]
Hi @ryan-224!
This file should be generated by pdb4amber, so probably something went wrong during the pdb4amber run. Check pdb4amber_reduce/pdb4amber.out in your working directory for any error messages.
